#!/bin/bash
# Usage: bash install_epstopdf

URL="https://tug.org/svn/texlive/trunk/Build/extra/epstopdf/epstopdf.pl?view=co"
sudo apt install -y wget
sudo wget "$URL" -O /usr/bin/epstopdf
sudo chmod +x /usr/bin/epstopdf
