#!/bin/bash
# This script installs MatCUTEst on Linux.

GIT_ORG="https://github.com/ralna"
GIT_ARCHDEFS="$GIT_ORG"/ARCHDefs
GIT_SIFDECODE="$GIT_ORG"/SIFDecode
GIT_CUTEST="$GIT_ORG"/CUTEst
GIT_MASTSIF="https://bitbucket.org/optrove/sif"
#GIT_MASTSIF="https://github.com/zaikunzhang/my_cutest_sif.git"
#GIT_MASTSIF="https://github.com/zaikunzhang/sif_test.git"

if [[ "$OSTYPE" != "linux-gnu"* ]]; then
    printf "\nThis package supports only GNU/Linux, not %s.\n\n" "$OSTYPE"
    exit 42
fi

printf "\nStart installing CUTEst for MATLAB ...\n"

printf "\nSetting environment variables ... \n"
# We assume that the architecture of the platformed is a Linux PC with 64 bit processors and gfortran.
MYARCH=pc64.lnx.gfo
# MATCUTEST is the root directory of MatCUTEst, i.e., the directory where this script resides.
MATCUTEST="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CUTEST="$MATCUTEST"/cutest
ARCHDEFS="$MATCUTEST"/archdefs
SIFDECODE="$MATCUTEST"/sifdecode
MASTSIF="$MATCUTEST"/sif
MATCUTEST_MTOOLS="$MATCUTEST"/mtools
PATH="$SIFDECODE"/bin:"$CUTEST"/bin:"$PATH"
# Set MYMATLAB to the directory of your MATLAB.
MYMATLAB="$(dirname "$(dirname "$(realpath "$(command -v matlab)")")")"
export CUTEST ARCHDEFS SIFDECODE MASTSIF PATH MYMATLAB  # Needed.
printf "\nDone.\n"

printf "\nCloning the repos ...\n"
if [[ -d "$ARCHDEFS" ]] ; then
    printf "\n%s exists. Skip.\n" "$ARCHDEFS"
else
    printf "\n"
    git clone "$GIT_ARCHDEFS" "$ARCHDEFS"
fi
if [[ -d "$SIFDECODE" ]] ; then
    printf "\n%s exists. Skip.\n" "$SIFDECODE"
else
    printf "\n"
    git clone "$GIT_SIFDECODE" "$SIFDECODE"
fi
if [[ -d "$CUTEST" ]] ; then
    printf "\n%s exists. Skip.\n" "$CUTEST"
else
    printf "\n"
    git clone "$GIT_CUTEST" "$CUTEST"
fi
if [[ -d "$MASTSIF" ]] ; then
    printf "\n%s exists. Skip.\n" "$MASTSIF"
else
    printf "\n"
    git clone "$GIT_MASTSIF" "$MASTSIF"
fi
printf "\nDone.\n"

printf "\nInstalling CUTEst ...\n"
cd "$CUTEST" && "$ARCHDEFS"/install_optrove || exit 1
printf "\nDone.\n"

printf "\nVerifying the installation ...\n"
cd "$CUTEST"/src && make -f "$CUTEST"/makefiles/"$MYARCH" test
printf "\nDone.\n"

printf "\nMexifying CUTEst for usage in MATLAB. This may take some time ...\n"
rm -f "$MATCUTEST_MTOOLS"/GOTCUP
cd "$MATCUTEST_MTOOLS" && matlab -nosplash -nodesktop -nodisplay -r "setup; exit" || exit 2
printf "\nDone.\n"

printf "\nRemove directories that are not needed anymore ...\n"
rm -rf "$ARCHDEFS" "$SIFDECODE" "$MASTSIF"
printf "\nDone.\n"
