function list = github_black_list()
%GITHUB_BLACK_LIST returns a list of problems that are blocked for GitHub Actions.

list = [];

% The following problems cause GitHub Actions to terminate unexpectedly.
list = [list, { ...
    'A0ENDNDL', ...
    'A0ENDNDL', ...
    'A0ENINDL', ...
    'A0ENSNDL', ...
    'A0ESDNDL', ...
    'A0ESINDL', ...
    'A0ESSNDL', ...
    'A2ENDNDL', ...
    'A2ENINDL', ...
    'A2ENINDL', ...
    'A2ENSNDL', ...
    'A2ESDNDL', ...
    'A2ESINDL', ...
    'A2ESSNDL', ...
    'A5ENDNDL', ...
    'A5ENINDL', ...
    'A5ENSNDL', ...
    'A5ESDNDL', ...
    'A5ESINDL', ...
    'A5ESSNDL', ...
    ‘BRAINPC2’, ...
    'CYCLOOCF', ...
    'CYCLOOCT', ...
    'EG3', ...
    'LOBSTERZ', ...
    'LUKVLI1', ...
    'MODBEALENE', ...
    'NINE5D', ...
    'OPTMASS', ...
    'ROSEPETAL2', ...
    }];
