function list = new_list()
%NEW_LIST returns the list of the new problems added by an update of CUTEst. We will check whether
% any of them should be included into the blacklist or not.

list = { ...
    'LRA9A', ...
    'LRCOVTYPE', ...
    'LRIJCNN1', ...
    'LRW1A', ...
    'LRW8A', ...
    };
