function list = test_list()
%TEST_LIST returns a short list of problems for testing whether MatCUTEst works as expected.

list = { ...
    'AKIVA', ...
    'BOX2', ...
    'ZECEVIC2', ...
    'ZANGWIL3', ...  % Feasibility problem
    'ZY2', ...
    %'TRIDIA', ...  % 20260912: mexification of TRIDIA fails, which did not happen before June 2026.
    };
