function list = test_list()
%TEST_LIST returns a short list of problems for testing whether MatCUTEst works as expected.

list = { ...
    'AKIVA', ...
    'BOX2', ...
    'ZECEVIC2', ...
    'ZY2', ...
    };
